const swaggerAutogen = require('swagger-autogen')();


const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:5000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json']
}


const outputFile = './swagger_output.json';
const endpointsFiles = ['./app.js','./api/auth/controller/auth.js','./api/blog/controller/blog.js','./core/routes.js']; // root file where the route starts.

swaggerAutogen(outputFile, endpointsFiles,doc).then(() => {
    require('./app.js');           // Your project's root file
})